name: Unit Tests, prettier, lint and build
on:
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com/"
          token: ${{secrets.GITHUB_TOKEN}}
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
